utils::globalVariables("fit_curve")

#' Optimize 5PL models to OpenArray PCR data and save as metadata
#' 
#' @description
#' 
#' Computes 5-parameter logistic models optimized to PCR data contained in the 
#' specified assay matrix, either `fluo_normalized` or `fluo_reporter`. The 
#' former refers to the base-line adjusted, normalized fluorescence from the 
#' `Amplification Data` tab of the original Excel output. The latter refers to
#' the multicomponent fluorescence from the `Multicomponent Data` tab. 
#' 
#' The expected input for this function is a SummarizedExperiment object 
#' containing OpenArray PCR data, which can be generated by calling the 
#' `excelToSE()` function of the package on the raw Excel output from
#' QuantStudio software.
#' 
#' @details 
#' 
#' Under the hood, this function invokes .runFitCurve(), a thin wrapper which 
#' calls python3 code to fit models with scipy.optimize, on each PCR reaction 
#' of the OpenArray plate separately. The computed models are added to the 
#' SummarizedExperiment container in metadata, named as `assay_name` + 
#' `_models`. For example, `fluo_normalized_models` would be created in the 
#' experiment metadata if `computeModels(assay_name = "fluo_normalized")` is
#' called.
#'
#' @param se OpenArray PCR data as a SummarizedExperiment object
#' @param assay_name character value specifying the assay matrix from which to 
#' load PCR data for curve-fitting, either `fluo_normalized` or `fluo_reporter`
#' @param linear_threshold numeric value specifying the minimum overall 
#' change-in-fluorescence over the PCR reaction required for the optimizer 
#' to attempt fitting a logistic model
#'
#' @returns OpenArray PCR data as a SummarizedExperiment object with
#' information from the computed model stored as metadata. 
#' 
#' @import S4Vectors
#' @import SummarizedExperiment
#' 
#' @importFrom rlang .data
#' 
#' @export
#'
#' @examples
#' path <- system.file(
#'     "extdata", 
#'     "oa_gene_expression_1.xlsx", 
#'     package = "OAtools"
#' )
#' 
#' se <- excelToSE(excel_path = path) |> 
#'     computeModels(assay_name = "fluo_normalized") |> 
#'     computeModels(assay_name = "fluo_reporter")
computeModels <- function(se, assay_name, linear_threshold = 400) {
    
    # set up named vector of PCR wells
    wells <- colnames(se)
    names(wells) <- wells
    
    # save fluorescence matrix and cycle numbers
    cycles <- rowData(se)$cycle
    fluo <- assay(se, assay_name)
    
    # optimize model curves for each PCR well; save to experiment metadata
    metadata(se)[[paste0(assay_name, "_models")]] <- purrr::map(
        wells,
        function(well) {
            .runFitCurve(
                data.frame(cycle = cycles, fluo = as.numeric(fluo[, well])),
                linear_threshold
            )
        }
    )
    
    return(se)
}

#' Run the fit_curve() function
#' 
#' A thin R wrapper for the python3 function fit_curve(), which attempts to 
#' optimize 5-parameter logistic regressions to PCR fluorescence curves. 
#'
#' @param pcr_data A `data.frame` with the following required columns: 
#' \describe{
#'     \item{cycle}{PCR cycle number}
#'     \item{fluo}{observed fluorescence}
#' }
#' @param linear_threshold numeric value specifying the minimum overall 
#' change-in-fluorescence over the PCR reaction required for the optimizer 
#' to attempt fitting a logistic model 
#' 
#' @import basilisk
#' @import reticulate
#'
#' @returns The model as a nested list
.runFitCurve <- function(pcr_data, linear_threshold) {
    basiliskRun(
        env = OAtools_env,
        fun = function() {
            source_python(system.file(
                "python", 
                "fit_curve.py", 
                package = "OAtools"
            ))
            return(fit_curve(pcr_data, linear_threshold))
        }
    )
}
