#' Curve fit data
#'
#' @description
#' This R tibble (.rda) contains qPCR and model curve data in tidyverse-friendly format.
#'
#' @details
#' Example R objects are stored in the `data/` directory of the package. Access this file with:
#'
#' `curve_fit_data`
#'
#' @format An R tibble (`.rda`) with fifteen columns:
#' \describe{
#'   \item{well}{integer value representing the well number of the reaction}
#'   \item{well_position}{factor value representing the well corresponding to the reaction}
#'   \item{sample_name}{factor storing name of the sample}
#'   \item{target_name}{factor storing name of the assay target}
#'   \item{crt}{numeric value for relative cycle threshold output by QS 12K Flex Software}
#'   \item{amp_score}{numeric value for amplification score output by QS 12K Flex Software}
#'   \item{cq_conf}{numeric value for confidence in Cq call output by QS 12K Flex Software}
#'   \item{amp_status}{factor storing run outcome as called by QS 12K Flex Software}
#'   \item{cycle}{integer value for cycle number}
#'   \item{fam}{numeric value for multicomponent fluorescence recorded at the given cycle number}
#'   \item{batch_name}{factor storing run name associated with the plate}
#'   \item{regression_type}{character string denoting type of regression computed for the reaction}
#'   \item{x_mid}{numeric cycle point at which the model curve crosses the midpoint between its minimal and maximal values; set to 40 for linear models}
#'   \item{slope}{numeric slope of the model at the x_mid cycle point}
#'   \item{delta}{numeric value approximating total change in fluorescence over the reaction}
#' }
#'
#' @source
#' Generated by calling the append_fit_results() function on the example tidy_run_data with
#' a linear threshold of 400.
#'
#' @keywords
#' data
#'
#' @name
#' curve_fit_data
NULL
