#' OA qPCR Data from a Gene Expression Experiment
#' 
#' @docType data
#' 
#' @description
#' This example data (.rda) contains a sample of OpenArray gene expression data
#' from a respiratory pathogen screening experiment conducted at the UW
#' Virology lab on human nasal swabs. This file is intended for use with 
#' package examples, vignettes, and unit testing. It contains the data within 
#' an instance of the Bioconductor S4 class SummarizedExperiment.
#' 
#' @details
#' This data is stored in the 'data/' directory of the package.
#' Load into the environment with: `data(example_se)`
#' 
#' @format a SummarizedExperiment object with the following:
#' \describe{
#'     \item{colData}{metadata for each through-hole on the OpenArray Plate}
#'     \item{rowData}{cycles over the PCR reaction}
#'     \item{assay}{a matrix of fluorescence data for each through-hole on the
#'     OpenArray Plate over the PCR reaction}
#' }
#' 
#' @source generated by running the excelToSummarizedExperiment() and
#' fitModelsToSe() functions on excel data exported from QuantStudio 12K Flex 
#' software following a gene expression experiment. 
#' 
#' @keywords
#' data
#' 
#' @name
#' example_se
NULL