#' Example OpenArray Gene Expression Data Contained in a SummarizedExperiment
#' 
#' @docType data
#' 
#' @description
#' A sample of OpenArray gene expression data from respiratory tract microbiota
#' profiling experiments conducted at the UW Virology research lab on human 
#' nasal swabs. This file (.rda) stores the PCR data in a SummarizedExperiment
#' container and is intended for use with package examples and unit testing.
#' 
#' @details
#' Load this object into the environment with: `data(example_se)`
#' 
#' @format a SummarizedExperiment object with the following:
#' \describe{
#'     \item{colData}{information associated with each PCR well}
#'     \item{rowData}{cycle numbers}
#'     \item{assays}{matrices of fluorescence values by PCR well and cycle}
#' }
#' 
#' @source generated by running the following commands:
#' 
#' `filename <- "oa_gene_expression_1.xlsx"`
#' 
#' `path <- system.file("extdata", filename, package = "OAtools")`
#' 
#' `example_se <- excelToSE(excel_path = path)`
#' 
#' `example_se <- example_se |> fitModelsToSE(linear_threshold = 400)`
#' 
#' @keywords
#' data
#' 
#' @name
#' example_se
NULL